apiVersion: v1
kind: Service
metadata:
  name: springboot-app
  labels:
    app: springboot-app
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: springboot-app
    tier: springboot-app
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: springboot-app
 namespace: default
spec:
 selector:
  matchLabels:
    app: springboot-app
 replicas: 1
template:
  metadata:
    labels:
      app: springboot-app
  spec:
    containers:
      - name: springboot-app
        image: dockerImage
        ports:
          - containerPort: 8090
        livenessProbe:
          httpGet:
            path: /health
            port: 8091
        readinessProbe:
          httpGet:
            path: /health
            port: 8091
